### ISSUE TITLE
Error on resuming upload (502)

### ISSUE THREAD

**Issue by vortexhoe** [jjmutumi/tus_client#11]
```dart
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: ProtocolException: unexpected status code (502) while resuming upload
E/flutter (10241): #0      TusClient._getOffset (package:myvideovault/src/client.dart:221:7)
E/flutter (10241): <asynchronous suspension>
E/flutter (10241): #1      TusClient.upload (package:myvideovault/src/client.dart:131:21)
E/flutter (10241): <asynchronous suspension>
E/flutter (10241): #2      tusUpload (package:myvideovault/globals/apis/profile/grabvideo.dart:173:16)
E/flutter (10241): <asynchronous suspension>
E/flutter (10241): #3      uploadVideoN (package:myvideovault/globals/apis/profile/grabvideo.dart:83:26)
E/flutter (10241): <asynchronous suspension>
E/flutter (10241): #4      _CameraState._onStopButtonPressed.<anonymous closure> (package:myvideovault/ui/account/camera/camera.dart:597:17)
E/flutter (10241): <asynchronous suspension>
E/flutter (10241): #5      _CameraState._onStopButtonPressed.<anonymous closure> (package:myvideovault/ui/account/camera/camera.dart)
E/flutter (10241): #6      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10241): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10241): #8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (10241): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (10241): #10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (10241): #11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (10241): #12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (10241): #13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (10241): #14     CameraController.stopVideoRecording (package:camera/src/camera_controller.dart)
E/flutter (10241): <asynchronous suspension>
E/flutter (10241): #15     _CameraState._stopVideoRecording (package:myvideovault/ui/account/camera/camera.dart:612:26)
E/flutter (10241): #16     _CameraState._onStopButtonPressed (package:myvideovault/ui/account/camera/camera.dart:546:5)
E/flutter (10241): #17     _CameraState._captureControlRowWidget.<anonymous closure> (package:myvideovault/ui/account/camera/camera.dart:457:23)
E/flutter (10241): #18     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (10241): #19     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (10241): #20     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (10241): #21     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (10241): #22     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (10241): #23     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (10241): #24     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (10241): #25     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (10241): #26     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (10241): #27     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (10241): #28     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (10241): #29     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (10241): #30     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (10241): #31     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (10241): #32     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (10241): #33     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (10241): #34     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (10241): #35     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10241): #36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10241): #37     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (10241): #38     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (10241):
```

Code: 
```dart
Future<void> tusUpload(Map options) async {
  final uploadurl = options["uploadurl"];
  final filepath = options["filepath"];
  final fname = options["filename"];
  var token = options["token"];
  var otherpath = options["TUS"];
  XFile _file = XFile(filepath);

  // Directory the current uploads will be saved in
  final tempDir = (await getTemporaryDirectory()).path;
  final tempDirectory = Directory(join(tempDir, "tus-uploads"));

  final client = TusClient(Uri.parse(uploadurl), _file,
      headers: {"Authorization": "Bearer $token"});

  await client.upload(
    onComplete: () async {
      print("Completed!");
    },
    onProgress: (progress) {
      print("Progress: $progress");
    },
  );
}
```

The above method is called upon stoppage of video recording through flutter's camera plugin: https://pub.dev/packages/camera

The camera plugin's stopVideoRecording() method returns an XFile that is then sent in a map passed to tusUpload along with other file options and stuff.

I've tried creating the client with including a URL persistent store and without and none of them seem to change the 502 error. If needed for context, the server requiring the TUS protocol is Cloudflare's Stream and documentation can be found here: 
https://developers.cloudflare.com/stream/uploading-videos/upload-video-file#resumable-uploads-with-tus-for-large-files

**Comment by jjmutumi** [comment]
Which version are you using?

Also try changing the chunk size as required by Cloudflare: 

> Important: Cloudflare Stream requires a minimum chunk size of 5,242,880 bytes when using TUS, unless the entire file is less than this amount.
> 
> We recommend increasing the chunk size to 52,428,800 bytes for better performance when the client connection is expected to be reliable.

https://developers.cloudflare.com/stream/uploading-videos/upload-video-file#what-is-tus

Like shown in the README:
```dart
final client = TusClient(
    Uri.parse("https://master.tus.io/files/"),
    file,
    maxChunkSize: 10 * 1024 * 1024,  // chunk is 10MB
);
```

**Comment by vortexhoe** [comment]
I'm using version 0.0.4 of your plugin, changing the chunk size doesn't change the result. I debugged the code a bit and the HEAD request (where the 502 is thrown and executed under _getOffset) seems to be the problem. Making an identically similar request in Postman (a popular API client) results in 200 rather than 502.

**Comment by jjmutumi** [comment]
Well the 502 error is coming from the server! So it doesn't like some part of the request the client is sent.

You can try these things:

1. Upgrading to 0.1.1
2. Explicitly setting chunk size to a minimum **5242880 bytes** or a multiple of **256KiB** as **required** by Cloudflare server **(This is missing in your sample code)**
3. Check the `uploadUrl` you are using
4. Check that the `token` is correct

Hope one of these steps helps you out!

**Comment by vortexhoe** [comment]
Unfortunately, trying all of your suggestions did not work. I'm using your example application currently just changing the client instantiation like so (main.dart:92): 
```dart
_client = TusClient(
  Uri.parse("https://upload.videodelivery.net/tus/e64e5f71ddda9d789c30e62c57c80412?tusv2=true"),
  _file,
  store: TusMemoryStore(),
  maxChunkSize: 5242880
);
```

Where the request fails, it fails here. (src/client.dart) : 
```dart
final response = await client.head(_uploadUrl, headers: offsetHeaders);

if (!(response.statusCode >= 200 && response.statusCode < 300)) {
   throw ProtocolException(
     "unexpected status code (${response.statusCode}) while resuming upload");
}
```

Some print symbols show the upload url is passed correctly and the only header is Tus-Resumable.

```dart
Future<int> _getOffset() async {
    final client = getHttpClient();

    final offsetHeaders = Map<String, String>.from(headers ?? {})
      ..addAll({
        "Tus-Resumable": tusVersion,
      });
    final response = await client.head(_uploadUrl, headers: offsetHeaders);

    print("offset :" + _uploadUrl.toString());
    print("offset headers: " + offsetHeaders.toString());

    if (!(response.statusCode >= 200 && response.statusCode < 300)) {
      throw ProtocolException(
          "unexpected status code (${response.statusCode}) while resuming upload");
    }

    int serverOffset = _parseOffset(response.headers["upload-offset"]);
    if (serverOffset == null) {
      throw ProtocolException(
          "missing upload offset in response for resuming upload");
    }
    return serverOffset;
  }
```

```
I/flutter ( 5240): Create a client
I/flutter ( 5240): Starting upload
I/flutter ( 5240): create: 201
I/flutter ( 5240): PASSED CREATE
I/flutter ( 5240): offset :https://upload.videodelivery.net/tus/e64e5f71ddda9d789c30e62c57c80412?tusv2=true
I/flutter ( 5240): offset headers: {Tus-Resumable: 1.0.0}
E/flutter ( 5240): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: ProtocolException: unexpected status code (502) while resuming upload
```

So, something is wrong with the HEAD request the http client is making, i'm not exactly sure what it is but like before, an identically similar request in Postman gives a good response (200).

Postman request: 
```
HEAD /tus/e64e5f71ddda9d789c30e62c57c80412?tusv2=true HTTP/1.1
Tus-Resumable: 1.0.0
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Cache-Control: no-cache
Postman-Token: 6afd6291-b4b4-48d2-a288-0e1c0e4aa1c6
Host: upload.videodelivery.net
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

HTTP/1.1 200 OK
Date: Mon, 04 Jan 2021 10:31:25 GMT
Connection: keep-alive
CF-Ray: 60c44a2c199ef1ae-ATL
Access-Control-Allow-Origin: *
Cache-Control: private
Strict-Transport-Security: max-age=15552000
CF-Cache-Status: DYNAMIC
access-control-allow-headers: Origin, Tus-Resumable, Tus-Version, Location, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Max-Size, Tus-Extension, Tus-Resumable, Upload-Defer-Length, X-HTTP-Method-Override, Content-Type
access-control-allow-methods: GET, POST, PATCH, HEAD
access-control-expose-header: cf-ray
access-control-expose-headers: Tus-Resumable, Tus-Version, Location, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Max-Size, Tus-Extension, Content-Type
cf-request-id: 076e8caf8e0000f1aef234c000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Served-In-Seconds: 0.090
stream-dw-version: 2020.12.1
stream-media-id: e64e5f71ddda9d789c30e62c57c80412
tus-resumable: 1.0.0
upload-length: 3967382
upload-offset: 0
x-content-type-options: nosniff
Vary: Accept-Encoding
Server: cloudflare
```

**Comment by jjmutumi** [comment]
Not quite sure what the query parameter **tusv2=true** on the URL? The client currently only supports version 1.0.0.

That aside I see the `upload-offset` is present in the response from postman. There could possibly be a problem how the `_parseOffset()`. Could you debug the value of `response.headers`?

**Comment by vortexhoe** [comment]
The parameter in the url seems to have no important role in the request considering it was present in the Postman request while the header was 1.0.0. I will grab the response headers for the offset request and share them in a bit as requested. 

I think it would particularly useful to follow network traffic coming from the example to compare the Postman HEAD request to dart HttpClient HEAD request and I will try that as well.

**Comment by vortexhoe** [comment]
Here is the debug output with response headers on 502.
```
I/flutter ( 7776): Create a client
I/flutter ( 7776): Starting upload
I/flutter ( 7776): create: 201
I/flutter ( 7776): PASSED CREATE
I/flutter ( 7776): offset :https://upload.videodelivery.net/tus/e64e5f71ddda9d789c30e62c57c80412?tusv2=true
I/flutter ( 7776): offset headers: {Tus-Resumable: 1.0.0}
I/flutter ( 7776): response offset headers: {connection: keep-alive, date: Mon, 04 Jan 2021 11:26:22 GMT, cf-request-id: 076ebf016a0000fa0351a89000000001, vary: Accept-Encoding, strict-transport-security: max-age=15552000, content-length: 28, cf-ray: 60c49aaf1952fa03-ATL, content-type: text/plain;charset=UTF-8, expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct", server: cloudflare}  
```

**Comment by jjmutumi** [comment]
@vortexhoe I'm thinking this is a dart:io bug. Track it here: https://github.com/dart-lang/sdk/issues/44583

**Comment by LAIMX** [comment]
I have some question about **__getData()_** function

the chunk size is always 65536

because the line
`final fileChunk = await file.openRead(start, end).first`

.first always return a 65536 size 

how to resolve it with custom size??

thanks a lot 

Derek

**Comment by jjmutumi** [comment]
@LAIMX Please open a new issue. But I wonder why would you want the size to be custom? Are you wanting to limit the [chunk size](https://github.com/jjmutumi/tus_client#changing-chunk-size)?

**Comment by BboyKeen** [comment]
@vortexhoe Using the beta version of Dart gets rid of the aforementioned issue

Take a look at https://github.com/dart-lang/sdk/issues/44583

**Comment by jjmutumi** [comment]
Yes @BboyKeen it should be updating dart SDK to get the fix.

@vortexhoe you can follow [this guide](https://flutter.dev/docs/development/tools/sdk/upgrading) and switch to the `beta` channel. You should make sure SDK version that includes the [commit `6c254fa`](https://github.com/dart-lang/sdk/commit/6c254fab89adbeebfb616cdec497260db4cb7cf7) (**2.15.0-6.0.dev** is the current as I write this) run:

```
flutter doctor -v
```
